default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: db/development.sqlite3
  cable:
    <<: *default
    database: db/development_cable.sqlite3
  queue:
    <<: *default
    database: db/development_queue.sqlite3
  cache:
    <<: *default
    database: db/development_cache.sqlite3

test:
  <<: *default
  database: home_stats_test

production:
  primary: &primary
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  
cable:
  <<: *primary
  database: <%= ENV.fetch('DATABASE_URL', '').sub(/\/?$/, '_cable') %>

queue:
  <<: *primary
  database: <%= ENV.fetch('DATABASE_URL', '').sub(/\/?$/, '_queue') %>
  
cache:
  <<: *primary
  database: <%= ENV.fetch('DATABASE_URL', '').sub(/\/?$/, '_cache') %>
